// Generated by wxt
export {}
declare global {
  const ANALYSIS_PROMPT: typeof import('C:/Users/yinal/Fake News Reader/src/utils/prompts')['ANALYSIS_PROMPT']
  const ContentScriptContext: typeof import('wxt/utils/content-script-context')['ContentScriptContext']
  const DEFAULTS: typeof import('C:/Users/yinal/Fake News Reader/src/utils/storage')['DEFAULTS']
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/utils/match-patterns')['MatchPattern']
  const analyzeArticle: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisOperations')['analyzeArticle']
  const browser: typeof import('wxt/browser')['browser']
  const buildAnalysisPrompt: typeof import('C:/Users/yinal/Fake News Reader/src/utils/prompts')['buildAnalysisPrompt']
  const cleanAndParseJSON: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisProcessor')['cleanAndParseJSON']
  const cleanupTabStates: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['cleanupTabStates']
  const cleanupUrlStorage: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['cleanupUrlStorage']
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']
  const createTimerFunctions: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisHelpers')['createTimerFunctions']
  const defineAppConfig: typeof import('wxt/utils/define-app-config')['defineAppConfig']
  const defineBackground: typeof import('wxt/utils/define-background')['defineBackground']
  const defineContentScript: typeof import('wxt/utils/define-content-script')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']
  const deleteTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['deleteTabState']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const fetchGemini: typeof import('C:/Users/yinal/Fake News Reader/src/utils/aiHandling')['fetchGemini']
  const fetchOpenAI: typeof import('C:/Users/yinal/Fake News Reader/src/utils/aiHandling')['fetchOpenAI']
  const generateSearchQuery: typeof import('C:/Users/yinal/Fake News Reader/src/utils/webSearch')['generateSearchQuery']
  const getDefaultState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['getDefaultState']
  const getMulti: typeof import('C:/Users/yinal/Fake News Reader/src/utils/storage')['getMulti']
  const getPageInfo: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisOperations')['getPageInfo']
  const getProvidersFromEnvironment: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisHelpers')['getProvidersFromEnvironment']
  const getStorage: typeof import('C:/Users/yinal/Fake News Reader/src/utils/storage')['getStorage']
  const getTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['getTabState']
  const getUrlAnalysis: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['getUrlAnalysis']
  const handleAnalyzeArticle: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleAnalyzeArticle']
  const handleGetPageInfo: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleGetPageInfo']
  const handleGetTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleGetTabState']
  const handleLoadAnalysisInTab: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleLoadAnalysisInTab']
  const handleNavigateAndReopenSidebar: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleNavigateAndReopenSidebar']
  const handlePreloadUrlAnalysis: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handlePreloadUrlAnalysis']
  const handleResetTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleResetTabState']
  const handleSaveTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleSaveTabState']
  const handleWebSearch: typeof import('C:/Users/yinal/Fake News Reader/src/utils/messageHandlers')['handleWebSearch']
  const injectScript: typeof import('wxt/utils/inject-script')['injectScript']
  const isTabBeingSetup: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['isTabBeingSetup']
  const loadAnalysisForUrl: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisOperations')['loadAnalysisForUrl']
  const markTabAsBeingSetup: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['markTabAsBeingSetup']
  const performWebSearch: typeof import('C:/Users/yinal/Fake News Reader/src/utils/webSearch')['performWebSearch']
  const processAnalysisResults: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisProcessor')['processAnalysisResults']
  const saveTabState: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['saveTabState']
  const setStorage: typeof import('C:/Users/yinal/Fake News Reader/src/utils/storage')['setStorage']
  const setUrlAnalysis: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['setUrlAnalysis']
  const shouldExpandSidebar: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisHelpers')['shouldExpandSidebar']
  const shouldSkipAutoAnalysis: typeof import('C:/Users/yinal/Fake News Reader/src/utils/analysisHelpers')['shouldSkipAutoAnalysis']
  const storage: typeof import('wxt/utils/storage')['storage']
  const testWebSearchLogging: typeof import('C:/Users/yinal/Fake News Reader/src/utils/webSearch')['testWebSearchLogging']
  const unmarkTabAsBeingSetup: typeof import('C:/Users/yinal/Fake News Reader/src/utils/tabState')['unmarkTabAsBeingSetup']
  const useAnalysisState: typeof import('C:/Users/yinal/Fake News Reader/src/hooks/useAnalysisState')['useAnalysisState']
  const useAppConfig: typeof import('wxt/utils/app-config')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useChromeStorage: typeof import('C:/Users/yinal/Fake News Reader/src/utils/useChromeStorage')['useChromeStorage']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useLayoutRefresh: typeof import('C:/Users/yinal/Fake News Reader/src/hooks/useLayoutRefresh')['useLayoutRefresh']
  const useMemo: typeof import('react')['useMemo']
  const useMessageHandlers: typeof import('C:/Users/yinal/Fake News Reader/src/hooks/useMessageHandlers')['useMessageHandlers']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { AnalysisResult } from 'C:/Users/yinal/Fake News Reader/src/utils/analysisProcessor'
  import('C:/Users/yinal/Fake News Reader/src/utils/analysisProcessor')
  // @ts-ignore
  export type { InjectedSidebarPerDomainState, RecentAnalysis, StorageShape } from 'C:/Users/yinal/Fake News Reader/src/utils/storage'
  import('C:/Users/yinal/Fake News Reader/src/utils/storage')
  // @ts-ignore
  export type { TabState } from 'C:/Users/yinal/Fake News Reader/src/utils/tabState'
  import('C:/Users/yinal/Fake News Reader/src/utils/tabState')
  // @ts-ignore
  export type { WebSearchResponse } from 'C:/Users/yinal/Fake News Reader/src/utils/webSearch'
  import('C:/Users/yinal/Fake News Reader/src/utils/webSearch')
}
