// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { useAnalysisState } from '../src/hooks/useAnalysisState';
  export { useMessageHandlers } from '../src/hooks/useMessageHandlers';
  export { shouldSkipAutoAnalysis, shouldExpandSidebar, getProvidersFromEnvironment } from '../src/utils/analysisHelpers';
  export { getPageInfo, analyzeArticle, loadAnalysisForUrl } from '../src/utils/analysisOperations';
  export { AnalysisResult } from '../src/utils/analysisProcessor';
  export { callBackendAnalyze, callBackendWebSearch } from '../src/utils/backendClient';
  export { handleGetPageInfo, handleAnalyzeArticle, handleGetTabState, handleResetTabState, handleSaveTabState, handleWebSearch, handleLoadAnalysisInTab, handleNavigateAndReopenSidebar, handlePreloadUrlAnalysis } from '../src/utils/messageHandlers';
  export { ANALYSIS_PROMPT, buildAnalysisPrompt } from '../src/utils/prompts';
  export { DEFAULTS, getStorage, setStorage, getMulti, InjectedSidebarPerDomainState, RecentAnalysis, StorageShape } from '../src/utils/storage';
  export { getDefaultState, saveTabState, getTabState, deleteTabState, isTabBeingSetup, markTabAsBeingSetup, unmarkTabAsBeingSetup, cleanupTabStates, TabState } from '../src/utils/tabState';
}
